### ISSUE TITLE
Set up auto deploys from main branch to dev environment

### ISSUE THREAD

**Issue by mrengy** [mrengy/vanguard-history#28]
https://github.com/marketplace/actions/branch-deploy

**Comment by mrengy** [comment]
Asked [question in Stack Overflow](https://stackoverflow.com/questions/74946906/how-to-automatically-deploy-main-branch-changes-to-staging-site-using-github-act)

**Comment by shekharkhedekar** [comment]
I think you might be able to use one of these https://github.com/marketplace?type=actions&query=ssh+

The workflow might look something like this:

```yml
name: Deploy latest main to stage
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      # https://github.com/marketplace/actions/ssh-remote-commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        # You might have to cd to the repo and pull here
        script: git pull
```
